config/routes.rb
OmotoFriends::Application.routes.draw do
  root 'home#index'

  resources :items do
    #collection do
    #  post 'upload'
    #end
    resources :comments
    resources :photos do
      collection do
        post 'upload'
      end
    end
  end

  resources :users, except: [:new, :create]

  resources :user_sessions
  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :item
  belongs_to :user

  attr_accessor :file, :temp_file

  validate :_valid_file?, if: -> { file }

  def tempfile_path
    "/images/tmp/#{Pathname.new(@temp_file).basename}"
  end

  def create_tempfile
    temp_file = Tempfile.new(['upload', '.jpg'], './public/images/tmp')
    @temp_file = temp_file.path

    img = Magick::Image.read(file.path).first

    # 撮影日時
    self.taken_at = _exif_datetime(img)

    if img.rows > 2000 || img.columns > 2000
      # これから縮小指定される可能性もあるので大きめにしておく
      img.resize_to_fit! 2000
    end
    img.auto_orient!

    img.write @temp_file
    true
  rescue => e
    logger.error e.backtrace.join "\n"
    false
  end

  def create_and_convert_image
    #TODO: 適当な暗号っぽいファイル名を作る
    #TODO 画像処理は非同期実行するとかだと良さそうな気がする
    #TODO: ファイルは会員IDのDIRに入れると良さそう
    new_file_path = "/usr/share/nginx/images/#{user_id.to_s(16)}"
    FileUtils.mkdir_p new_file_path

    self.id = sequence_nextval
    self.path = (item_id * 100_000 + id).to_s(16)

    #TODO magick number of 1024
    max_size = 1024
    img = Magick::Image.read(@temp_file).first
    if img.rows > max_size || img.columns > max_size
      img.resize_to_fit! max_size
    end
    img.strip!
    #TODO should move to Image.class
    write_image img, "#{new_file_path}/#{self.path}.jpg"

    # make thumbnail
    x, y = [img.columns, img.rows]
    mx = my = 320
    my = my * (y.to_f / x) if x > y
    mx = mx * (x.to_f / y) if x < y
    img.thumbnail! mx.to_i, my.to_i
    write_image img, "#{new_file_path}/#{self.path}_s.jpg"
  end

  private

  def _exif_datetime(img)
    exif_time = img.get_exif_by_entry('DateTimeOriginal').first
    DateTime.strptime(exif_time[1], '%Y:%m:%d %H:%M:%S') if exif_time
  end

  def _valid_file?
    if file.content_type != 'image/jpeg'
      self.errors[:file] << 'photo-file should jpeg'
    end
  end

  def sequence_nextval
    next_seq = self.connection.execute("SELECT nextval('photos_id_seq')")
    next_seq[0]['nextval']
  end

  def write_image(img, path)
    img.write path
    FileUtils.chmod 0664, path
  end

  def file_path=(value)
    if File.exist? value
      @temp_file = value
    end
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]
  before_action :set_item

  def show
    @photos = @item.photos
  end

  def new
    @photo = Photo.new
  end

  def upload
    @photo = Photo.new file: params[:file]

    unless @photo.valid? && @photo.create_tempfile
      @photo.errors << '写真アップロードエラー'
      render :new, notice: 'upload failed'
    end
  end

  def create
    @photo = Photo.new(photo_params)
    #@photo[:temp_file] = params[:temp_file]

    if File.exist? @photo.temp_file
      @item.add_photo @photo
      redirect_to @item
    else
      render action: 'new', notice: 'temp image file not found'
    end
  end

  def edit
  end

  def update
  end

  def destory
  end

  private

  def set_photo
    @photo = Photo.find(params[:id])
  end

  def set_item
    @item = Item.find(params[:item_id])
  end

  def photo_params
    params.permit :item_id, :user_id, :path, :description, :taken_at, :temp_file
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_adjust.html.haml
.image-pane
  /TODO これをポップアップか何かにしたい
  / 編集ボタンだけにしておいて、ポップアップ上？とかで編集させる
  / 初回アップロード時のUIと共通化するなら、そのままでも良さそう
  / 写真編集の確定ボタンでAjaxで画像加工座標情報とかだけPostする
  %span.image-frame
    = image_tag image_path(@item), class: 'main-image'

  / 画像の回転ボタン
  %button.image-manipulate.rotate-r.btn.btn-warning.btn-sm
    %i.fa.fa-rotate-right
  %button.image-manipulate.rotate-l.btn.btn-warning.btn-sm
    %i.fa.fa-rotate-left

  / 画像のサイズ調整ボタン (top / botton)
  %button.image-manipulate.top.left-side.btn.btn-info.btn-sm
    %i.fa.fa-arrow-down
  %button.image-manipulate.top.btn.btn-warning.btn-sm
    %i.fa.fa-arrow-up
  %button.image-manipulate.bottom.left-side.btn.btn-info.btn-sm
    %i.fa.fa-arrow-up
  %button.image-manipulate.bottom.btn.btn-warning.btn-sm
    %i.fa.fa-arrow-down

  / 画像のサイズ調整ボタン (left / right)
  %button.image-manipulate.left.over.btn.btn-info.btn-sm
    %i.fa.fa-arrow-right
  %button.image-manipulate.left.btn.btn-warning.btn-sm
    %i.fa.fa-arrow-left
  %button.image-manipulate.right.over.btn.btn-info.btn-sm
    %i.fa.fa-arrow-left
  %button.image-manipulate.right.btn.btn-warning.btn-sm
    %i.fa.fa-arrow-right

  / 画像変更保存ボタン
  %button.image-manipulate.save.btn.btn-primary
    %i.fa.fa-cloud-upload &nbsp;変更を保存

app/views/photos/_form.html.haml
.field
  = f.label :description
  %br
  = f.text_area :description, rows: 2
.field
  = f.label '撮影日時: '
  = f.datetime_local_field :taken_at, class: 'datetime'
.actions
  = f.submit '変更を確定する', class: 'btn btn-primary btn-lg'
.clear

app/views/photos/edit.html.haml
/%h1 Editing item
/TODO: remove page name but bread crum on header-line ?

- conf_msg = 'おもと情報を削除すると投稿した画像と一緒に元に戻せなくなります。よろしいですか？'
= render partial: 'layouts/errors', locals: {obj: @item}

.item-view
  .image-pane
    - if @item.photos.empty?
      %span.image-frame
        まだ画像がアップロードされていません
    - else
      /TODO これをポップアップか何かにしたい
      / 編集ボタンだけにしておいて、ポップアップ上？とかで編集させる
      / 初回アップロード時のUIと共通化するなら、そのままでも良さそう
      / 写真編集の確定ボタンでAjaxで画像加工座標情報とかだけPostする
      %span.image-frame
        = image_tag image_path(@item), class: 'main-image'
      / 画像の回転ボタン
      %button.image-manipulate.rotate-r.btn.btn-warning.btn-sm
        %i.fa.fa-rotate-right
      %button.image-manipulate.rotate-l.btn.btn-warning.btn-sm
        %i.fa.fa-rotate-left
      / 画像のサイズ調整ボタン (top / botton)
      %button.image-manipulate.top.left-side.btn.btn-info.btn-sm
        %i.fa.fa-arrow-down
      %button.image-manipulate.top.btn.btn-warning.btn-sm
        %i.fa.fa-arrow-up
      %button.image-manipulate.bottom.left-side.btn.btn-info.btn-sm
        %i.fa.fa-arrow-up
      %button.image-manipulate.bottom.btn.btn-warning.btn-sm
        %i.fa.fa-arrow-down
      / 画像のサイズ調整ボタン (left / right)
      %button.image-manipulate.left.over.btn.btn-info.btn-sm
        %i.fa.fa-arrow-right
      %button.image-manipulate.left.btn.btn-warning.btn-sm
        %i.fa.fa-arrow-left
      %button.image-manipulate.right.over.btn.btn-info.btn-sm
        %i.fa.fa-arrow-left
      %button.image-manipulate.right.btn.btn-warning.btn-sm
        %i.fa.fa-arrow-right
      / 画像変更保存ボタン
      %button.image-manipulate.save.btn.btn-primary
        %i.fa.fa-cloud-upload &nbsp;変更を保存
    .thumb
      %ul
        - @item.photos.each do |photo|
          %li.thumb-list
            = image_tag photo_thumbnail_path(photo)
      %span.thumb-add
        = link_to new_item_photo_path(@item) do
          %button{class: 'btn btn-warning'}
            %i.fa.fa-plus

  .info-pane
    .edit.field
      = link_to @item do
        %button{class: 'btn btn-default'} 変更をやめる
      = link_to @item, method: :delete, data: {confirm: conf_msg} do
        %button{class: 'btn btn-danger'} 削除
    = form_for @item do |f|
      = render partial: 'form', locals: {f: f}

app/views/photos/index.html.haml
%h1 みんなのおもと

- @items.each do |item|
  .list-item
    = link_to item, class: 'item-link' do
      .item-image
        - unless item.photos.empty?
          = image_tag thumbnail_path(item)
        - else
          %span No Image
      .item-title
        = item.title
    .item-info
      .item.owner
        = link_to user_path(item.user) do
          %span.text= item.user.name
      .item.breed
        品種:
        %span.text= item.breed
      /.item.desc
      /  %span= item.description
.clear

app/views/photos/new.html.haml
%ol.breadcrumb.process
  %li
    %button{class: 'btn btn-success'} 写真アップロード
  %li 写真の調整・情報入力
  %li 登録完了

%h1 おもと写真を登録する

= render partial: 'layouts/errors', locals: {obj: @photo}

= form_tag(upload_item_photos_path(@item), multipart: true) do |f|
  .field
    %p
      登録したいおもとの写真をアップロードします。次の画面で正式登録します
    = label_tag :file
    %br/
    = file_field_tag :file
  .actions.submit
    = submit_tag '写真の調整・情報入力に進む', {class: 'btn btn-primary'}

%hr
= link_to items_path do
  %button{class: 'btn btn-default'} アップロードをやめる

app/views/photos/show.html.haml
.item-view
  .image-pane
    %span.image-frame
      - if @item.photos.empty?
        %span.main-image
          まだ写真がアップロードされていません
      - else
        = image_tag image_path(@item), class: 'main-image'
      .thumb
        %ul
          - @item.photos.each do |photo|
            %li.thumb-list
              = image_tag photo_thumbnail_path(photo)
  .info-pane
    - if current_user && current_user.id == @item.user.id
      .edit.field
        = link_to edit_item_path(@item) do
          %button{class: 'btn btn-warning'} 変更/写真を追加する
    .field.title
      %span.field-value
        = "「 #{@item.title} 」"
    .field
      品種:
      %span.field-value
        = @item.breed
    .field
      .desc-text
        = raw(h(@item.description).gsub(/\n/, '<br>'))
    %hr
    .comments
      - @item.comments.each do |comment|
        .field.comment
          = link_to user_path comment.user do
            = comment.user.name
          &nbsp;:
          %span.field-value
            = comment.body
      - if current_user
        .field
          = form_tag item_comments_path(@item), method: :post do |f|
            .comment-input
              .comment-text
                = text_area_tag :body, nil, rows: 2, class: 'form-control comment'
              .comment-submit
                = button_tag '送信', class: 'btn btn-info comment'

  .clear

app/views/photos/upload.html.haml
= render partial: 'layouts/errors', locals: {obj: @photo}

.item-view
  .image-pane
    %span.image-frame
      = image_tag @photo.tempfile_path, class: 'main-image'
    %button.rotate.rotate-r.btn.btn-warning.btn-sm
      %i.fa.fa-rotate-right
    %button.rotate.rotate-l.btn.btn-warning.btn-sm
      %i.fa.fa-rotate-left
  .info-pane
    = form_for [@item, @photo] do |f|
      = hidden_field_tag :temp_file, @photo.temp_file
      = render partial: 'form', locals: {f: f}
  .clear