config/routes.rb
OmotoFriends::Application.routes.draw do
  root 'home#index'

  resources :items do
    #collection do
    #  post 'upload'
    #end
    resources :comments
    resources :photos do
      collection do
        post 'upload'
      end
    end
  end

  resources :users, except: [:new, :create]

  resources :user_sessions
  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_filter :require_login, except: [:destroy]

  def new
    @user = User.new
    session[:return_to_url] = session[:previous_url]
  end

  def create
    if @user = login(params[:email], params[:password], params[:remember])
      redirect_back_or_to :root, notice: 'ログインしました'
      session[:return_to_url] = nil
    else
      @user = User.new(email: params[:email])
      flash.now[:alert] = "ログインできません。メールアドレスかパスワードが間違っています"
      render action: :new
    end
  end

  def destroy
    logout
    redirect_to :root, notice: 'ログアウトしました'
  end

  private

  def login_params     # Strong parameters
    params.require(:user)
      .permit(:email, :password, :password_confirmation, :remember)
  end
end

app/views/user_sessions/new.html.haml
%h1 ログイン

.signin-wrapper
  .signin-contents
    .signin-form
      = form_tag user_sessions_path, method: :post do
        .field
          = label_tag :email
          .input
            = email_field_tag :email, @user.email, autofocus: true, size:25
        .field
          = label_tag :password
          .input
            = password_field_tag :password, size: 25
        /- if devise_mapping.rememberable?
        /  %div
        /    = f.check_box :remember_me
        /    = f.label :remember_me
        .action.submit.field
          %label
          .input
            = submit_tag 'ログイン', class: 'button'
        /.field
        /  %label
        /  .input
        /    = link_to new_password_path(resource_name) do
        /      パスワードを忘れた場合

    .signin-links
      /= link_to new_registration_path(resource_name) do
      .button
        会員登録