config/routes.rb
OmotoFriends::Application.routes.draw do
  root 'home#index'

  resources :items do
    #collection do
    #  post 'upload'
    #end
    resources :comments
    resources :photos do
      collection do
        post 'upload'
      end
    end
  end

  resources :users, except: [:new, :create]

  resources :user_sessions
  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout
end

app/views/layouts/_errors.html.haml
/ "obj" is controller object
- if obj.errors.any?
  #error_explanation
    %h2
      = pluralize(obj.errors.count, "error")
      prohibited this item from being saved:
    %ul
      - obj.errors.full_messages.each do |msg|
        %li= msg

app/views/layouts/_footer.html.haml
%hr.footer
.footer-line
  \&copy;kato Ippei 2014

app/views/layouts/_header.html.haml
.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{type: "button", data: {toggle: "collapse", target: ".navbar-collapse"} }
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to root_path, class: "navbar-brand" do
        #top-title
          /%span.logo
          %span.logo-title
            おもとも！
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li{ class: root_now? ? 'active' : '' }
          = link_to root_path do
            %i.fa.fa-home>
            \&nbsp;Home
        %li{ class: items_now? ? 'active' : '' }
          = link_to items_path do
            %i.fa.fa-pagelines>
            \&nbsp;おもと
        %li{ class: users_now? ? 'active' : '' }
          = link_to users_path do
            %i.fa.fa-users>
            \&nbsp;Users
        /%li
        /  %a{:href => "/map"}
        /  .menu-item
        /    %span.menu-text ご近所
        %li{ class: upload_now? ? 'active' : '' }
          = link_to new_item_path do
            %i.fa.fa-upload>
            \&nbsp;アップロード

      %ul.nav.navbar-nav.navbar-right
        - if current_user
          %li.dropdown
            %a.dropdown-toggle{href: "#", "data-toggle" => "dropdown"}
              %i.fa.fa-user
              = current_user.name
              %b.caret
            %ul.dropdown-menu
              %li
                = link_to 'マイページ', user_path(current_user)
              %li
                %a{href:"#"}
                  %i.fa.fa-gear
                  設定
              %li.divider
              %li
                = link_to logout_path do
                  %i.icon-signout>
                  ログアウト
        - else
          %li
            = link_to login_path do
              %i.icon-signin>
              ログイン

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta{charset: "utf-8"}
    %meta{content: "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no", name: "viewport"}

    / Le HTML5 shim, for IE6-8 support of HTML5 elements
    /TODO いらないようにしたい
    /[if lt IE 9]
    /  = javascript_include_tag "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"
    /  = javascript_include_tag "https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"

    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    %link{href: "//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css", rel: "stylesheet"}/
    %link{rel:"stylesheet", href:"//sample.beco-ippei.net/slidery/css/jquery.slidery.css"}
    = javascript_include_tag "application"
    = csrf_meta_tags

    %title OmotoFriends #TODO app_name
  %body
    = render partial: 'layouts/header'

    #state

    .container
      - flash.each do |name, msg|
        = content_tag :div, class: "alert alert-#{name == :error ? "danger" : "success" } alert-dismissable" do
          %button.close{type: "button", data: {dismiss: "alert"}, aria: {hidden: "true"} } &times;
          = msg
      = yield
      .clear
      %footer
        = render partial: 'layouts/footer'

    #footer-meta